{
  "name": "backend",
  "version": "1.0.0",
  "description": "Backend for Agri-Energy Connect",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "bcrypt": "^5.1.1",
    "body-parser": "^1.20.2",
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "express-brute": "^1.0.1",
    "express-rate-limit": "^7.3.1",
    "helmet": "^7.1.0",
    "jsonwebtoken": "^9.0.2",
    "mongoose": "^8.3.1",
    "morgan": "^1.10.0"
  },
  "devDependencies": {
    "eslint": "^9.0.0",
    "nodemon": "^3.1.0"
  }
}
